version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./client:/app

  redis:
    image: "redis:alpine"
